[package]
name = "escpos2png"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
escpos2png-profiles = { path = "../escpos2png-profiles" }
fontdue.workspace = true
oem_cp.workspace = true
png.workspace = true
thiserror.workspace = true

[dev-dependencies]
escpos2png-profiles = { path = "../escpos2png-profiles" }

[lints]
workspace = true
